### ISSUE TITLE
Simplify long argument lists

### ISSUE THREAD

**Issue by danieldietrich** [danieldietrich/copy#19]
The argument lists of `rename`, `transform`, `filter` and `afterEach` are relatively long. From the user-perspective, it would be nice to simplify the API.

```ts
// current API
transform: (data: Buffer, source: string, target: string, sourceStats: fs.Stats, targetStats?: fs.Stats) => { ... }
forEach: (source: string, target: string, sourceStats: fs.Stats, targetStats: fs.Stats) => { ... }

// suggested API
transform: (data: Buffer, source: Path, target: PathOption) => { ... }
forEach: (source: Path, target: Path) => { ... }

type Path = { path: string, stats: fs.Stats };
type PathOption = { path: string, stats?: fs.Stats };
```

---

@wickedest you depend on the API, I would appreciate to have your feedback. This would be a breaking change. We follow semantic versioning, so it would go to the next major version 1.0.0.

I'm always open to naming suggestions...

**Comment by danieldietrich** [comment]
I've drafter it and I think that the types are clearer this way. The lambdas are now more concise and we abstract over similarities of source and target. I will prepare the 1.0 release in order to ship it.

**Comment by wickedest** [comment]
I agree - it's cleaner. They were quite long and repetitive. Though, they're not *paths*. They are more like a FileInfo. Also, Path and Path Option are exactly the same and could use the same type. Either way, it's an improvement.

**Comment by danieldietrich** [comment]
@wickedest thanks! Then let's get this right.

> They are more like a FileInfo

You are right, I will change that.

> Also, Path and Path Option are exactly the same

Not exactly, PathOption has an _optional_ stats property. I wanted to make it clear on the type system that the _stats_ property is defined when afterEach is called. However, when taking you following [comment](https://github.com/danieldietrich/copy/issues/18) into account the picture changes. 

> Though, it isn't great that it won't be called in a dry-run

I agree about that. It would make sense to remove FileInfoOption and make _stats_ optional. In a dry-run, the target.stats will be undefined. In a non-dry-run, target.stats will be defined. That way, source and target will always be of type FileInfo and we are able to call afterEach in a dry-run. The user 'just' has to check target.stats in order to decide whether to perform file system changes or not.

I think that is a good compromise.

Many thanks for your great feedback. I will prepare a new major release. I follow semantic versioning, that will be a breaking change again, sorry for that.

\- Daniel

**Comment by danieldietrich** [comment]
**Update:** There is a problem when having FileInfo only with an optional stats property: source.stats may be undefined all over the code, which produces compile errors. I think it is not an option to add additional checks, if source.stats is defined.

We need one FileInfo type with a stats field that is never undefined and one FileInfo type that may be undefined. There are two options:

1. Having two types FileInfo and FileInfoOption (as before with Path and PathOption)

2. Parameterizing FileInfo like this:

```ts
type FileInfo<T extends never | undefined> = {
    path: string;
    stats: fs.Stats | T;
};

// usage:
function afterEach(source: FileInfo<never>, target: FileInfo<undefined>): void | Promise<void>;
```

In copy@1.0.0 I chose two distinct types Path and PathOption because it is a more direct way to express the types. Not all users are familiar with generics in depth.

What do you think? Should we take solution 1. or 2. (see above)?

**Comment by wickedest** [comment]
For the record, 0.x.y is for non stable API. Pretty sure a minor bump on a caret semver ^0.x.y is the same a major change. I'd have to opt in to the change. You do not need to do a 1.0.0.

**Comment by wickedest** [comment]
I wouldn't know ts, so I'd be biased to option 1

**Comment by danieldietrich** [comment]
Thx! I did a 1.0.0 already this night 🙈 now it is there for eternity.

I am preparing the PR. After your review we will release the changes...

**Comment by danieldietrich** [comment]
@wickedest please find the newest version on [npmjs.com](https://www.npmjs.com/package/@danieldietrich/copy).

**Comment by danieldietrich** [comment]
> For the record, 0.x.y is for non stable API. Pretty sure a minor bump on a caret semver ^0.x.y is the same a major change.

@wickedest I fixed the versions by unpublishing the major changes from npm. The most recent version is now 0.4.1. I have a much better feeling about that because we are still in the process of doing backward incompatible changes.

**Comment by wickedest** [comment]
@danieldietrich, tried out the 0.4.2 release and it's working great.  The Source/Target change makes things much cleaner.  thanks, and nice work!

**Comment by danieldietrich** [comment]
@wickedest Thank you for your feedback and for your contribution! Your ideas were really important to me.
